/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_angzangy_aalive_muxer_RtmpMuxer */

#ifndef _Included_org_angzangy_aalive_muxer_RtmpMuxer
#define _Included_org_angzangy_aalive_muxer_RtmpMuxer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_angzangy_aalive_muxer_RtmpMuxer
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_angzangy_aalive_muxer_RtmpMuxer_init
  (JNIEnv *, jobject);

/*
 * Class:     org_angzangy_aalive_muxer_RtmpMuxer
 * Method:    open
 * Signature: (JLjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_org_angzangy_aalive_muxer_RtmpMuxer_open
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     org_angzangy_aalive_muxer_RtmpMuxer
 * Method:    writeVideo
 * Signature: (J[BIIJ)I
 */
JNIEXPORT jint JNICALL Java_org_angzangy_aalive_muxer_RtmpMuxer_writeVideo
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jlong);

/*
 * Class:     org_angzangy_aalive_muxer_RtmpMuxer
 * Method:    writeNioVideo
 * Signature: (JLjava/nio/ByteBuffer;IIJ)I
 */
JNIEXPORT jint JNICALL Java_org_angzangy_aalive_muxer_RtmpMuxer_writeNioVideo
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jlong);

/*
 * Class:     org_angzangy_aalive_muxer_RtmpMuxer
 * Method:    writeAudio
 * Signature: (J[BIIJ)I
 */
JNIEXPORT jint JNICALL Java_org_angzangy_aalive_muxer_RtmpMuxer_writeAudio
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jlong);

/*
 * Class:     org_angzangy_aalive_muxer_RtmpMuxer
 * Method:    writeNioAudio
 * Signature: (JLjava/nio/ByteBuffer;IIJ)I
 */
JNIEXPORT jint JNICALL Java_org_angzangy_aalive_muxer_RtmpMuxer_writeNioAudio
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jlong);

/*
 * Class:     org_angzangy_aalive_muxer_RtmpMuxer
 * Method:    read
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_org_angzangy_aalive_muxer_RtmpMuxer_read
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_angzangy_aalive_muxer_RtmpMuxer
 * Method:    close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_angzangy_aalive_muxer_RtmpMuxer_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_angzangy_aalive_muxer_RtmpMuxer
 * Method:    writeFlvHeader
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_org_angzangy_aalive_muxer_RtmpMuxer_writeFlvHeader
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     org_angzangy_aalive_muxer_RtmpMuxer
 * Method:    fileOpen
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_angzangy_aalive_muxer_RtmpMuxer_fileOpen
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_angzangy_aalive_muxer_RtmpMuxer
 * Method:    fileClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_angzangy_aalive_muxer_RtmpMuxer_fileClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_angzangy_aalive_muxer_RtmpMuxer
 * Method:    isConnected
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_angzangy_aalive_muxer_RtmpMuxer_isConnected
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_angzangy_aalive_muxer_RtmpMuxer
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_angzangy_aalive_muxer_RtmpMuxer_release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
