/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_angzangy_aalive_OpenglNative */

#ifndef _Included_org_angzangy_aalive_OpenglNative
#define _Included_org_angzangy_aalive_OpenglNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_angzangy_aalive_OpenglNative
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_angzangy_aalive_OpenglNative_init
  (JNIEnv *, jobject);

/*
 * Class:     org_angzangy_aalive_OpenglNative
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_angzangy_aalive_OpenglNative_release
  (JNIEnv *, jobject);

/*
 * Class:     org_angzangy_aalive_OpenglNative
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_angzangy_aalive_OpenglNative_onSurfaceCreated
  (JNIEnv *, jobject);

/*
 * Class:     org_angzangy_aalive_OpenglNative
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_angzangy_aalive_OpenglNative_onSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_angzangy_aalive_OpenglNative
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_angzangy_aalive_OpenglNative_onDrawFrame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
